import { IsString, IsInt, IsOptional, Min, IsNotEmpty } from 'class-validator';

export class CreateClassroomDto {
  @IsInt()
  @IsOptional()
  id?: number; // Optional field for ID, generally auto-generated by the database

  @IsString()
  @IsNotEmpty()
  name: string;

  @IsInt()
  @Min(1)
  capacity: number;
}

export class ClassroomDto {
    id: number;
    name: string;
    capacity: number;
    createdAt: Date;
    updatedAt: Date;
  }